package apply

import (
	"io/fs"

	"github.com/yuanying/regied/internal/apis/v1alpha1"
	"github.com/yuanying/regied/internal/config"
	"github.com/yuanying/regied/internal/render/dnsmasq"
	"github.com/yuanying/regied/internal/render/networkd"
	"github.com/yuanying/regied/internal/render/nftables"
	"github.com/yuanying/regied/internal/render/pppd"
)

// The defaults the renderers name for what regied owns.
const (
	defaultRoot     = pppd.DefaultRoot
	defaultStateDir = dnsmasq.DefaultStateDirectory
)

// ownershipMarker is the first line of every file regied writes that is not in a
// directory where the file name already says whose it is. It is how reclaiming tells our
// files from everybody else's in a shared directory (ADR 0009).
//
// It is the same line the dnsmasq and pppd renderers write, and TestRenderedFilesCarry-
// TheOwnershipMarker holds the two together.
const ownershipMarker = "# Generated by regied. Do not edit: every apply rewrites this file."

// artifact is one file an apply would put on the host. The four renderers each have
// their own file type, deliberately: they were built to be independent of one another.
// This is the small adapter that receives them all.
type artifact struct {
	Path    string
	Mode    fs.FileMode
	DirMode fs.FileMode
	Content string
	Secret  bool
}

// rendering is everything the four backends produced for one configuration.
type rendering struct {
	artifacts []artifact
	warnings  []string

	// ruleset is the text to hand to nft.
	ruleset string
	// sessions is every PPPoESession's name, in the order the document lists them.
	sessions []string
	// dnsmasq is whether this host needs one at all.
	dnsmasq bool
}

// render turns a validated configuration and the values read from the host into every
// file, plus the ruleset. Nothing here touches the host: this is still the staging
// stage (ADR 0004).
func (e *Engine) render(cfg *config.Config, runtime *Runtime) (*rendering, error) {
	out := &rendering{}

	links, err := networkd.Render(cfg, runtime.Networkd)
	if err != nil {
		return nil, err
	}
	out.warnings = append(out.warnings, links.Warnings...)
	for _, file := range links.Files {
		out.artifacts = append(out.artifacts, artifact{
			Path:    e.opts.NetworkdDir + "/" + file.Name,
			Mode:    file.Mode,
			DirMode: 0o755,
			Content: file.Content,
		})
	}

	out.ruleset, err = renderRuleset(cfg, runtime.NFTables)
	if err != nil {
		return nil, err
	}

	sessions := pppd.Render(cfg, pppd.WithRoot(e.opts.Root))
	for _, session := range sessions.Sessions {
		out.sessions = append(out.sessions, session.Name)
		out.artifacts = append(out.artifacts, fromPPPdFile(session.Peer))

		credentials, ok := runtime.Credentials[session.Name]
		if !ok {
			// CollectRuntime refuses a configuration whose credentials it could not
			// read, so this cannot be reached from Apply. Failing loudly here keeps a
			// future caller from writing an options file with no account in it.
			return nil, &RuntimeError{Problems: []string{
				"PPPoESession/" + session.Name + ": no credentials were read for this session",
			}}
		}
		file, err := session.Credentials.Render(credentials)
		if err != nil {
			return nil, &RuntimeError{Problems: []string{
				"PPPoESession/" + session.Name + ": " + err.Error(),
			}}
		}
		out.artifacts = append(out.artifacts, fromPPPdFile(file))
	}

	names := dnsmasq.Render(cfg, dnsmasq.WithRoot(e.opts.Root), dnsmasq.WithStateDirectory(e.opts.StateDir))
	for _, file := range names.Files() {
		out.dnsmasq = true
		out.artifacts = append(out.artifacts, artifact{
			Path:    file.Path,
			Mode:    file.Mode,
			DirMode: file.DirMode,
			Content: file.Content,
			Secret:  file.Secret,
		})
	}

	out.artifacts = append(out.artifacts, e.units(out)...)
	return out, nil
}

// renderRuleset is the one table regied owns, as the text to hand to nft. It is the only
// rendering that depends on an uplink's address, which is why the last phase of an apply
// can call it on its own (ADR 0004).
func renderRuleset(cfg *config.Config, runtime nftables.Runtime) (string, error) {
	ruleset, err := nftables.Render(cfg, runtime)
	if err != nil {
		return "", err
	}
	return ruleset.String(), nil
}

func fromPPPdFile(file pppd.File) artifact {
	return artifact{
		Path:    file.Path,
		Mode:    file.Mode,
		DirMode: file.DirMode,
		Content: file.Content,
		Secret:  file.Secret,
	}
}

// kernelSwitch is one /proc/sys key and the value spec.global asks for.
type kernelSwitch struct{ key, value string }

// kernelSwitches is what spec.global means to the kernel.
//
// Several of the switches are two keys or four: forwarding and redirects are per family,
// and the per-interface ones are set on both `all` and `default` so that a link
// appearing later gets the same answer as the ones already there.
func kernelSwitches(global v1alpha1.Global) []kernelSwitch {
	on := func(enabled bool) string {
		if enabled {
			return "1"
		}
		return "0"
	}
	forwarding := on(global.IPForwardingEnabled())
	redirectsOut := on(global.SendRedirectsEnabled())
	redirectsIn := on(global.ReceiveRedirectsEnabled())
	martians := on(global.LogMartiansEnabled())
	// Reverse path filtering is a mode rather than a flag: 1 is strict, and strict is
	// what "on" means here. It stays off wherever policy routing is declared, because
	// policy routing is what makes return paths asymmetric (docs/spec/configuration.md).
	reversePath := on(global.SourceValidationEnabled())

	return []kernelSwitch{
		{"net.ipv4.ip_forward", forwarding},
		{"net.ipv6.conf.all.forwarding", forwarding},
		{"net.ipv4.tcp_syncookies", on(global.SynCookiesEnabled())},
		{"net.ipv4.conf.all.log_martians", martians},
		{"net.ipv4.conf.default.log_martians", martians},
		{"net.ipv4.conf.all.send_redirects", redirectsOut},
		{"net.ipv4.conf.default.send_redirects", redirectsOut},
		{"net.ipv4.conf.all.accept_redirects", redirectsIn},
		{"net.ipv4.conf.default.accept_redirects", redirectsIn},
		{"net.ipv6.conf.all.accept_redirects", redirectsIn},
		{"net.ipv6.conf.default.accept_redirects", redirectsIn},
		{"net.ipv4.conf.all.rp_filter", reversePath},
		{"net.ipv4.conf.default.rp_filter", reversePath},
	}
}
