// Package dnsmasq builds the dnsmasq configuration a host's DHCPServer and DNSForwarder
// resources add up to. There is one dnsmasq on a host, so there is one file: every
// resource of both kinds renders into it (docs/spec/configuration.md).
//
// Rendering is a pure function of the validated configuration. Nothing here reads the
// kernel, starts a process, or opens a file.
package dnsmasq

import (
	"fmt"
	"io/fs"
	"net"
	"net/netip"
	"strings"
	"time"

	"github.com/yuanying/regied/internal/apis/v1alpha1"
	"github.com/yuanying/regied/internal/config"
)

// Where the generated configuration and the lease database go. Both are regied's own:
// everything below them is rewritten on apply, and nothing regied did not write is there
// (ADR 0009). The distribution's own dnsmasq keeps its file elsewhere and is left alone.
const (
	DefaultRoot           = "/etc/regied"
	DefaultStateDirectory = "/var/lib/regied"
)

// ownershipMarker is the first line of the generated file. It says who wrote the file,
// so that a file without it is somebody else's and is left alone.
const ownershipMarker = "# Generated by regied. Do not edit: every apply rewrites this file."

// File is one file to put on the host: where it goes, what is in it, and how it and the
// directory holding it are protected.
type File struct {
	Path    string
	Mode    fs.FileMode
	DirMode fs.FileMode
	Content string

	// Secret says the content holds a credential (ADR 0003). Nothing dnsmasq is
	// configured with is one, so it is always false here; the field is there so that
	// every rendered file answers the question the same way.
	Secret bool
}

// Output is the one dnsmasq configuration a host's resources add up to. A host that
// declares neither kind needs no dnsmasq, and then there is no file: Config is the zero
// value and Files is empty.
type Output struct {
	Config File
}

// Files is what to put on the host.
func (o *Output) Files() []File {
	if o.Config.Path == "" {
		return nil
	}
	return []File{o.Config}
}

// Option changes where the rendered files are put.
type Option func(*options)

type options struct {
	root  string
	state string
}

// WithRoot puts the generated configuration under a directory other than DefaultRoot.
func WithRoot(dir string) Option {
	return func(o *options) { o.root = dir }
}

// WithStateDirectory puts the lease database under a directory other than
// DefaultStateDirectory.
func WithStateDirectory(dir string) Option {
	return func(o *options) { o.state = dir }
}

func resolveOptions(opts []Option) options {
	resolved := options{root: DefaultRoot, state: DefaultStateDirectory}
	for _, opt := range opts {
		opt(&resolved)
	}
	return resolved
}

// Render builds the dnsmasq configuration for cfg.
func Render(cfg *config.Config, opts ...Option) *Output {
	resolved := resolveOptions(opts)
	servers := config.ResourcesOf[*v1alpha1.DHCPServerSpec](cfg)
	forwarders := config.ResourcesOf[*v1alpha1.DNSForwarderSpec](cfg)

	// A host that hands out no addresses and resolves nothing has no reason to run
	// dnsmasq, so there is nothing to write.
	if len(servers) == 0 && len(forwarders) == 0 {
		return &Output{}
	}

	var b strings.Builder
	b.WriteString(ownershipMarker + "\n")
	b.WriteString("#\n")
	b.WriteString("# One dnsmasq serves every DHCPServer and DNSForwarder on the host. Router\n")
	b.WriteString("# advertisement is not here -- the interface sends it, so there is only ever\n")
	b.WriteString("# one sender.\n")

	writeInterfaces(&b, cfg, servers, forwarders)
	writeDNS(&b, forwarders)
	writeDHCP(&b, cfg, resolved, servers)

	return &Output{Config: File{
		Path:    resolved.root + "/dnsmasq/dnsmasq.conf",
		Mode:    0o644,
		DirMode: 0o755,
		Content: b.String(),
	}}
}

// writeInterfaces names the links dnsmasq answers on: every link a forwarder listens on,
// and every link a DHCP server serves.
func writeInterfaces(b *strings.Builder, cfg *config.Config,
	servers []config.Named[*v1alpha1.DHCPServerSpec], forwarders []config.Named[*v1alpha1.DNSForwarderSpec]) {

	var links []string
	seen := make(map[string]bool)
	add := func(ifname string) {
		if ifname == "" || seen[ifname] {
			return
		}
		seen[ifname] = true
		links = append(links, ifname)
	}
	for _, server := range servers {
		add(interfaceIfname(cfg, server.Spec.InterfaceRef))
	}
	for _, forwarder := range forwarders {
		for _, ref := range forwarder.Spec.ListenOn {
			add(linkIfname(cfg, ref))
		}
	}
	if len(links) == 0 {
		return
	}

	b.WriteString("\n")
	b.WriteString("# The links to answer on. bind-dynamic keeps dnsmasq off every other link,\n")
	b.WriteString("# the uplink included, while still coping with one that appears later.\n")
	b.WriteString("bind-dynamic\n")
	for _, ifname := range links {
		fmt.Fprintf(b, "interface=%s\n", ifname)
	}
}

func writeDNS(b *strings.Builder, forwarders []config.Named[*v1alpha1.DNSForwarderSpec]) {
	if len(forwarders) == 0 {
		// A host that hands out addresses but resolves nothing still runs dnsmasq. It
		// must not start answering on the segment because it happens to be listening.
		b.WriteString("\n")
		b.WriteString("# No DNSForwarder is declared, so this dnsmasq answers no queries.\n")
		b.WriteString("port=0\n")
		return
	}

	// A host declares at most one DNSForwarder: dnsmasq has one cache and one set of
	// upstreams, so a second one would ask the process for something it cannot do, and
	// validation refuses it (docs/spec/kinds.md).
	forwarder := forwarders[0]
	spec := forwarder.Spec

	b.WriteString("\n")
	b.WriteString("# DNS. The upstreams are declared, so the host resolver is not consulted: on\n")
	b.WriteString("# this host it is this process, and asking it would be a loop. Names come from\n")
	b.WriteString("# the configuration alone and not from /etc/hosts, and neither an unqualified\n")
	b.WriteString("# name nor a private reverse lookup is sent upstream.\n")
	b.WriteString("no-resolv\n")
	b.WriteString("no-poll\n")
	b.WriteString("no-hosts\n")
	b.WriteString("domain-needed\n")
	b.WriteString("bogus-priv\n")
	fmt.Fprintf(b, "cache-size=%d\n", spec.CacheSizeOrDefault())

	fmt.Fprintf(b, "\n# DNSForwarder/%s\n", forwarder.Name)
	for _, upstream := range spec.Upstreams {
		fmt.Fprintf(b, "server=%s\n", upstream)
	}
	// A server directive carries one address, so a zone answered by two resolvers is two
	// lines.
	for _, conditional := range spec.Conditional {
		for _, server := range conditional.Servers {
			fmt.Fprintf(b, "server=/%s/%s\n", conditional.Domain, server)
		}
	}
	// host-record answers exactly this name. address=/name/ would also answer for
	// everything below it, which is more than the schema says.
	for _, host := range spec.StaticHosts {
		fmt.Fprintf(b, "host-record=%s,%s\n", host.Name, host.Address)
	}
}

func writeDHCP(b *strings.Builder, cfg *config.Config, opts options,
	servers []config.Named[*v1alpha1.DHCPServerSpec]) {

	if len(servers) == 0 {
		return
	}
	b.WriteString("\n")
	b.WriteString("# DHCP\n")
	b.WriteString("dhcp-authoritative\n")
	fmt.Fprintf(b, "dhcp-leasefile=%s/dnsmasq.leases\n", opts.state)

	for _, server := range servers {
		writeDHCPServer(b, cfg, server)
	}
}

func writeDHCPServer(b *strings.Builder, cfg *config.Config, server config.Named[*v1alpha1.DHCPServerSpec]) {
	spec := server.Spec
	tag := server.Name

	fmt.Fprintf(b, "\n# DHCPServer/%s\n", server.Name)

	// The tag set here is what carries this server's options to the clients it answers.
	if spec.Pool != nil {
		fmt.Fprintf(b, "dhcp-range=set:%s,%s,%s,%s,%s\n", tag, spec.Pool.Start, spec.Pool.End,
			netmask(spec.Subnet.Prefix), duration(spec.LeaseTimeOrDefault()))
	}

	// Both default to the interface's own address. An interface whose only address is
	// derived from a delegated prefix has none written down, and dnsmasq's own default
	// is the same rule, so nothing is written for it.
	own := interfaceAddress(cfg, spec.InterfaceRef)
	if gateway := spec.Gateway; gateway != nil {
		fmt.Fprintf(b, "dhcp-option=tag:%s,option:router,%s\n", tag, gateway)
	} else if own.IsValid() {
		fmt.Fprintf(b, "dhcp-option=tag:%s,option:router,%s\n", tag, own)
	}
	if len(spec.DNSServers) > 0 {
		fmt.Fprintf(b, "dhcp-option=tag:%s,option:dns-server,%s\n", tag, join(spec.DNSServers, plain))
	} else if own.IsValid() {
		fmt.Fprintf(b, "dhcp-option=tag:%s,option:dns-server,%s\n", tag, own)
	}
	// Scoped to the subnet, so a second segment can carry a domain of its own.
	if spec.Domain != "" && spec.Subnet.IsValid() {
		fmt.Fprintf(b, "domain=%s,%s\n", spec.Domain, spec.Subnet.Masked())
	}

	for _, mapping := range spec.StaticMappings {
		fmt.Fprintf(b, "dhcp-host=%s,%s,%s\n", mapping.MACAddress, mapping.Address, mapping.Name)
	}

	if spec.IPv6 == nil {
		return
	}
	// Stateless DHCPv6: answer what a client asks for once the advertisement has told it
	// to ask. No ra- keyword appears, so dnsmasq sends no advertisement of its own --
	// the interface is the one sender (docs/spec/kinds.md, DHCPServer.ipv6).
	v6tag := tag + "-v6"
	fmt.Fprintf(b, "dhcp-range=set:%s,::,constructor:%s,static\n", v6tag, interfaceIfname(cfg, spec.InterfaceRef))
	fmt.Fprintf(b, "dhcp-option=tag:%s,option6:information-refresh-time,%s\n", v6tag,
		duration(spec.IPv6.InformationRefreshTimeOrDefault()))
	if len(spec.IPv6.DNSServers) > 0 {
		fmt.Fprintf(b, "dhcp-option=tag:%s,option6:dns-server,%s\n", v6tag, join(spec.IPv6.DNSServers, bracketed))
	}
}

// plain and bracketed are how an address is written in a DHCP option. dnsmasq wants a
// literal IPv6 address in brackets, so that the colons are not read as field separators.
func plain(addr v1alpha1.Addr) string     { return addr.String() }
func bracketed(addr v1alpha1.Addr) string { return "[" + addr.String() + "]" }

func join(addrs []v1alpha1.Addr, write func(v1alpha1.Addr) string) string {
	written := make([]string, len(addrs))
	for i, addr := range addrs {
		written[i] = write(addr)
	}
	return strings.Join(written, ",")
}

// netmask writes a prefix length the way a DHCP client wants it.
func netmask(prefix netip.Prefix) string {
	if !prefix.IsValid() || !prefix.Addr().Is4() {
		return ""
	}
	return net.IP(net.CIDRMask(prefix.Bits(), 32)).String()
}

// duration writes a time the way dnsmasq reads one. It takes a single unit, so a value
// that is not a whole number of the larger unit falls back to the smaller.
func duration(d time.Duration) string {
	switch {
	case d%time.Hour == 0:
		return fmt.Sprintf("%dh", int(d/time.Hour))
	case d%time.Minute == 0:
		return fmt.Sprintf("%dm", int(d/time.Minute))
	default:
		return fmt.Sprintf("%ds", int(d/time.Second))
	}
}

// interfaceAddress is the first address written out on an interface, which is what a
// gateway and a resolver default to. An address derived from a delegated prefix is not
// one: what it becomes is not known until the prefix is.
func interfaceAddress(cfg *config.Config, ref string) netip.Addr {
	spec := interfaceSpec(cfg, ref)
	if spec == nil {
		return netip.Addr{}
	}
	for _, address := range spec.Addresses {
		if address.IsLiteral() && address.Literal.Addr().Is4() {
			return address.Literal.Addr()
		}
	}
	return netip.Addr{}
}

// interfaceIfname is the kernel name of an Interface. Validation has already resolved the
// reference; the fallback is there so that a Config built by hand cannot make this panic.
func interfaceIfname(cfg *config.Config, ref string) string {
	if spec := interfaceSpec(cfg, ref); spec != nil {
		return spec.Ifname
	}
	return ref
}

// linkIfname is the kernel name of any link resource, plus the reserved name loopback.
// A PPPoE session and a DS-Lite tunnel put a link on the host named after the resource,
// so only an Interface has a name of its own to look up.
func linkIfname(cfg *config.Config, ref string) string {
	if ref == v1alpha1.LoopbackLink {
		return "lo"
	}
	return interfaceIfname(cfg, ref)
}

func interfaceSpec(cfg *config.Config, ref string) *v1alpha1.InterfaceSpec {
	resource := cfg.Lookup(v1alpha1.KindInterface, ref)
	if resource == nil {
		return nil
	}
	spec, _ := resource.Spec.(*v1alpha1.InterfaceSpec)
	return spec
}
