package networkd

import (
	"slices"
	"strings"
	"testing"
)

// An interface with addresses and an MTU is the simplest thing there is: one .network
// file, matched by kernel interface name.
func TestInterfaceAddressesAndMTU(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lab}
      spec:
        ifname: eth1
        mtu: 9000
        addresses:
          - 192.0.2.1/24
          - "2001:db8::1/64"
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out, "50-regied-lab.network")
	assertFile(t, out, "50-regied-lab.network", `# Generated by regied from Interface/lab. Do not edit.

[Match]
Name=eth1

[Link]
MTUBytes=9000

[Network]
Address=192.0.2.1/24
Address=2001:db8::1/64
IPv6AcceptRA=no
`)
}

// A bridge is a .netdev, a .network for the bridge itself, and one file per member that
// enslaves it. A member does not need an Interface resource of its own. The bridge is
// configured whether or not a member has link: its address is the segment's gateway,
// and no carrier on a bridge only means no client yet (ADR 0018).
func TestInterfaceBridge(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: br-lan
        bridge:
          members: [eth1, eth2]
        addresses:
          - 192.0.2.1/24
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out,
		"50-regied-lan-eth1.network",
		"50-regied-lan-eth2.network",
		"50-regied-lan.netdev",
		"50-regied-lan.network",
	)
	assertFile(t, out, "50-regied-lan.netdev", `# Generated by regied from Interface/lan. Do not edit.

[NetDev]
Name=br-lan
Kind=bridge

[Bridge]
STP=no
VLANFiltering=no
`)
	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=br-lan

[Network]
ConfigureWithoutCarrier=yes
Address=192.0.2.1/24
IPv6AcceptRA=no
`)
	assertFile(t, out, "50-regied-lan-eth1.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
LinkLocalAddressing=no
Bridge=br-lan
IPv6AcceptRA=no
`)
}

// A bridge with no member is the same bridge minus the files that enslave members: its
// ports are attached by something else, such as a container runtime, and it holds its
// address with none attached.
func TestInterfaceBridgeWithoutMembers(t *testing.T) {
	for _, bridge := range []string{`{}`, `{members: []}`} {
		t.Run(bridge, func(t *testing.T) {
			cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: br-lan
        bridge: `+bridge+`
        addresses:
          - 192.0.2.1/24
`)
			out := render(t, cfg, Runtime{})

			assertNames(t, out, "50-regied-lan.netdev", "50-regied-lan.network")
			assertFile(t, out, "50-regied-lan.netdev", `# Generated by regied from Interface/lan. Do not edit.

[NetDev]
Name=br-lan
Kind=bridge

[Bridge]
STP=no
VLANFiltering=no
`)
			assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=br-lan

[Network]
ConfigureWithoutCarrier=yes
Address=192.0.2.1/24
IPv6AcceptRA=no
`)
		})
	}
}

// A member declared as an Interface of its own — the way to give it a property that is
// its own, such as an MTU — is enslaved by its own file rather than by a second one.
func TestInterfaceBridgeMemberWithItsOwnResource(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: br-lan
        bridge:
          members: [eth1]
    - kind: Interface
      metadata: {name: port}
      spec:
        ifname: eth1
        mtu: 9000
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out, "50-regied-lan.netdev", "50-regied-lan.network", "50-regied-port.network")
	assertFile(t, out, "50-regied-port.network", `# Generated by regied from Interface/port. Do not edit.

[Match]
Name=eth1

[Link]
MTUBytes=9000

[Network]
LinkLocalAddressing=no
Bridge=br-lan
IPv6AcceptRA=no
`)
}

// Static routes leave by the link they are written on. A route with no next hop goes
// on-link through that interface.
// Wake-on-LAN goes in a .link file, which udev reads rather than networkd. It matches the
// declared name as OriginalName=, which is the name udev meets on the move event a rename
// sends (ADR 0020), and the apply engine is told which link each file is for.
func TestInterfaceWakeOnLan(t *testing.T) {
	cases := []struct {
		name, value, want string
	}{
		{"one mode", "magic", "magic"},
		{"a list", "[magic, unicast]", "magic unicast"},
		{"off", "off", "off"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eno1
        wakeOnLan: `+tc.value+`
        addresses:
          - 192.0.2.10/24
`)
			out := render(t, cfg, Runtime{})

			assertNames(t, out, "50-regied-lan.link", "50-regied-lan.network")
			assertFile(t, out, "50-regied-lan.link", `# Generated by regied from Interface/lan. Do not edit.

[Match]
OriginalName=eno1

[Link]
WakeOnLan=`+tc.want+`
`)
			want := []LinkFile{{Name: "50-regied-lan.link", Ifname: "eno1"}}
			if !slices.Equal(out.LinkFiles, want) {
				t.Errorf("the link files are %+v, want %+v", out.LinkFiles, want)
			}
		})
	}
}

// An Interface that leaves Wake-on-LAN out leaves the NIC alone, and gets no .link file.
func TestInterfaceWithoutWakeOnLanHasNoLinkFile(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eno1
        addresses:
          - 192.0.2.10/24
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out, "50-regied-lan.network")
	if len(out.LinkFiles) != 0 {
		t.Errorf("link files were reported for an Interface with none: %+v", out.LinkFiles)
	}
}

// The .link file depends on nothing read at apply time, so a link whose DUID has not been
// read still gets it while its .network waits.
func TestInterfaceWakeOnLanDoesNotWaitForTheDUID(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        wakeOnLan: magic
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
            duidFile: /etc/regied/duid
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out, "50-regied-wan.link")
	if len(out.Omitted) != 1 || !slices.Equal(out.Omitted[0].Files, []string{"50-regied-wan.network"}) {
		t.Errorf("want only the .network waiting for the DUID, got %+v", out.Omitted)
	}
}

func TestInterfaceRoutes(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses:
          - 192.0.2.1/24
        routes:
          - destination: 172.16.0.0/16
            via: 192.0.2.10
            metric: 50
          - destination: 198.51.100.0/24
          - destination: "2001:db8:0:2::/64"
            via: "2001:db8:0:1::10"
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
Address=192.0.2.1/24
IPv6AcceptRA=no

[Route]
Destination=172.16.0.0/16
Gateway=192.0.2.10
Metric=50

[Route]
Destination=198.51.100.0/24

[Route]
Destination=2001:db8:0:2::/64
Gateway=2001:db8:0:1::10
`)
}

// The upstream interface runs the DHCPv6 client, and it runs it for the delegation
// alone: the interface's own global address comes from SLAAC. The DUID is read at apply
// time, and networkd wants its type and its payload apart.
func TestInterfacePrefixDelegationClient(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          useDNS: false
          prefixDelegation:
            prefixLength: 56
            rapidCommit: true
            duidFile: /etc/regied/secrets/dhcpv6-duid
            iaid: 0
`)
	out := render(t, cfg, Runtime{DUIDs: map[string]string{
		"/etc/regied/secrets/dhcpv6-duid": "00:03:00:01:00:00:5e:00:53:01\n",
	}})

	assertFile(t, out, "50-regied-wan.network", `# Generated by regied from Interface/wan. Do not edit.

[Match]
Name=eth0

[Network]
DHCP=ipv6
IPv6AcceptRA=yes

[DHCPv6]
WithoutRA=solicit
UseAddress=yes
UseDNS=no
RapidCommit=yes
PrefixDelegationHint=::/56
DUIDType=link-layer
DUIDRawData=00:01:00:00:5e:00:53:01
IAID=0

[IPv6AcceptRA]
DHCPv6Client=always
UseDNS=no
`)
}

// The IAID is the other half of the client identity a provider binds the delegation to,
// and networkd's default is derived from the interface, so the router being replaced
// and the one replacing it never agree on it by accident. A declared value is written as
// given; zero is the usual one, and it has to be told apart from "not declared".
func TestInterfacePrefixDelegationIAID(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
            iaid: 7
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-wan.network", `# Generated by regied from Interface/wan. Do not edit.

[Match]
Name=eth0

[Network]
DHCP=ipv6
IPv6AcceptRA=yes

[DHCPv6]
WithoutRA=solicit
UseAddress=yes
UseDNS=no
RapidCommit=yes
PrefixDelegationHint=::/56
IAID=7

[IPv6AcceptRA]
DHCPv6Client=always
UseDNS=no
`)
}

// An address taken from the delegated prefix is not written out: the derivation is, so
// that everything built on the address follows a prefix change.
func TestInterfaceAddressFromDelegatedPrefix(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
            duidFile: /etc/regied/secrets/dhcpv6-duid
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: br-lan
        bridge:
          members: [eth1]
        addresses:
          - 192.0.2.1/24
          - fromDelegatedPrefix:
              interfaceRef: wan
              subnetID: 17
              token: "::1"
`)
	out := render(t, cfg, Runtime{DUIDs: map[string]string{
		"/etc/regied/secrets/dhcpv6-duid": "00:03:00:01:00:00:5e:00:53:01",
	}})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=br-lan

[Network]
ConfigureWithoutCarrier=yes
Address=192.0.2.1/24
IPv6AcceptRA=no
DHCPPrefixDelegation=yes

[DHCPPrefixDelegation]
UplinkInterface=eth0
SubnetId=0x11
Token=static:::1
Assign=yes
Announce=no
`)
}

// A host below a router accepts the advertisement and keeps only the token: the prefix
// comes from the wire. The default route and the DHCPv6 information request that follow
// an advertisement are networkd's defaults and are not written.
func TestInterfaceAddressFromRouterAdvertisement(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth0
        addresses:
          - 192.168.10.153/24
          - fromRouterAdvertisement:
              token: "::153"
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth0

[Network]
Address=192.168.10.153/24
IPv6AcceptRA=yes

[IPv6AcceptRA]
Token=static:::153
`)
}

// A DHCPv6 client and a token share the one [IPv6AcceptRA] section, and what the client
// writes there is unchanged.
func TestInterfaceAddressFromRouterAdvertisementWithDHCPv6(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        addresses:
          - fromRouterAdvertisement: {token: "::1"}
        dhcpv6:
          useDNS: true
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-wan.network", `# Generated by regied from Interface/wan. Do not edit.

[Match]
Name=eth0

[Network]
DHCP=ipv6
IPv6AcceptRA=yes

[DHCPv6]
UseAddress=yes
UseDNS=yes

[IPv6AcceptRA]
UseDNS=yes
Token=static:::1
`)
}

// An address from the advertisement is not advertised onward: only a literal prefix is,
// and nothing about the token or the prefix it lands in belongs to [DHCPPrefixDelegation].
func TestInterfaceAddressFromRouterAdvertisementIsNotAdvertised(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses:
          - "2001:db8:0:1::1/64"
          - fromRouterAdvertisement: {token: "::1"}
        ipv6:
          advertise:
            mode: slaac
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
Address=2001:db8:0:1::1/64
IPv6AcceptRA=yes
IPv6SendRA=yes

[IPv6AcceptRA]
Token=static:::1

[IPv6SendRA]
Managed=no
OtherInformation=no
EmitDNS=no

[IPv6Prefix]
Prefix=2001:db8:0:1::/64
PreferredLifetimeSec=43200
ValidLifetimeSec=86400
`)
}

// Router advertisement is networkd's. The prefix advertised is the one the interface
// holds, so it is not written in the advertisement either.
func TestInterfaceRouterAdvertisement(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses:
          - 192.0.2.1/24
          - "2001:db8:0:1::1/64"
        ipv6:
          advertise:
            mode: slaac
            otherInformation: true
            dnsServers: ["2001:db8:0:1::1"]
            validLifetime: 12h
            preferredLifetime: 3h
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
Address=192.0.2.1/24
Address=2001:db8:0:1::1/64
IPv6AcceptRA=no
IPv6SendRA=yes

[IPv6SendRA]
Managed=no
OtherInformation=yes
EmitDNS=yes
DNS=2001:db8:0:1::1

[IPv6Prefix]
Prefix=2001:db8:0:1::/64
PreferredLifetimeSec=10800
ValidLifetimeSec=43200
`)
}

// An advertisement with nothing but a delegated prefix to advertise hands the prefix to
// [DHCPPrefixDelegation], which takes its lifetimes from the delegation. A lifetime
// written here would be dropped, so it is reported rather than dropped quietly.
func TestInterfaceAdvertisedLifetimesNeedALiteralPrefix(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
            duidFile: /etc/regied/secrets/dhcpv6-duid
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses:
          - fromDelegatedPrefix:
              interfaceRef: wan
              subnetID: 1
        ipv6:
          advertise:
            mode: slaac
            validLifetime: 12h
`)
	out := render(t, cfg, Runtime{DUIDs: map[string]string{
		"/etc/regied/secrets/dhcpv6-duid": "00:03:00:01:00:00:5e:00:53:01",
	}})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
IPv6AcceptRA=no
IPv6SendRA=yes
DHCPPrefixDelegation=yes

[DHCPPrefixDelegation]
UplinkInterface=eth0
SubnetId=0x1
Assign=yes
Announce=yes

[IPv6SendRA]
Managed=no
OtherInformation=no
EmitDNS=no
`)
	if len(out.Warnings) != 1 || !strings.Contains(out.Warnings[0], "validLifetime") {
		t.Errorf("warnings are %q, want one about the advertised lifetimes", out.Warnings)
	}
}

// The DUID is not a secret and it is not read here either: the apply engine reads the
// file and hands the contents over. Without it the link's file is not rendered at all —
// a prefix delegation written without the DUID is not a smaller version of the one
// declared, it is a different configuration, under which the delegated prefix changes
// — and the rendering says what the file waits for (ADR 0016).
func TestInterfaceWithAnUnreadDUIDIsLeftOut(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
            duidFile: /etc/regied/secrets/dhcpv6-duid
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: br-lan
        bridge:
          members: [eth1]
        addresses: [192.168.10.1/24]
`)
	out := render(t, cfg, Runtime{})

	for _, file := range out.Files {
		if file.Name == "50-regied-wan.network" {
			t.Fatalf("the link's file was rendered without the DUID:\n%s", file.Content)
		}
	}
	if len(out.Omitted) != 1 {
		t.Fatalf("omitted %v, want exactly the link's file", out.Omitted)
	}
	omitted := out.Omitted[0]
	if omitted.Resource != "Interface/wan" {
		t.Errorf("the omission is attributed to %q, want Interface/wan", omitted.Resource)
	}
	if len(omitted.Files) != 1 || omitted.Files[0] != "50-regied-wan.network" {
		t.Errorf("the omission names %v, want the link's .network file", omitted.Files)
	}
	if !strings.Contains(omitted.Waiting, "/etc/regied/secrets/dhcpv6-duid") {
		t.Errorf("the omission does not name the file it waits for: %q", omitted.Waiting)
	}
	// Everything that does not depend on the DUID is rendered as usual.
	if len(out.Files) != 3 {
		t.Errorf("the rest of the rendering is missing; got %d files, want the bridge's netdev, its network and its member's", len(out.Files))
	}
}

// Omitting duidFile is legitimate, and then there is nothing to hand to networkd.
func TestInterfaceWithoutDUIDFile(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 60
            rapidCommit: false
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-wan.network", `# Generated by regied from Interface/wan. Do not edit.

[Match]
Name=eth0

[Network]
DHCP=ipv6
IPv6AcceptRA=yes

[DHCPv6]
WithoutRA=solicit
UseAddress=yes
UseDNS=no
RapidCommit=no
PrefixDelegationHint=::/60

[IPv6AcceptRA]
DHCPv6Client=always
UseDNS=no
`)
}

// networkd takes one [DHCPPrefixDelegation] section per link, so one interface cannot
// hold two addresses derived from the delegation.
func TestInterfaceTwoDelegatedAddresses(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses:
          - fromDelegatedPrefix: {interfaceRef: wan, subnetID: 1}
          - fromDelegatedPrefix: {interfaceRef: wan, subnetID: 2}
`)
	_, err := Render(cfg, Runtime{})
	if err == nil {
		t.Fatal("rendered two delegated addresses onto one link")
	}
	if !strings.Contains(err.Error(), "Interface/lan") {
		t.Errorf("the error does not name the interface: %v", err)
	}
}

// The DUID is split into the type networkd names and the payload it takes as hex.
func TestDUIDSplit(t *testing.T) {
	for _, c := range []struct {
		duid, kind, data string
	}{
		{"00:03:00:01:00:00:5e:00:53:01", "link-layer", "00:01:00:00:5e:00:53:01"},
		{"00:01:00:01:2f:3a:1b:4c:00:00:5e:00:53:01", "link-layer-time", "00:01:2f:3a:1b:4c:00:00:5e:00:53:01"},
		{"00:02:00:00:ab:11:f9:2a:c2:77", "vendor", "00:00:ab:11:f9:2a:c2:77"},
		{"00:04:0f:0e:0d:0c", "uuid", "0f:0e:0d:0c"},
		{"00:07:0f:0e", "7", "0f:0e"},
	} {
		kind, data, err := splitDUID(c.duid)
		if err != nil {
			t.Errorf("%s: %v", c.duid, err)
			continue
		}
		if kind != c.kind || data != c.data {
			t.Errorf("%s split into %s / %s, want %s / %s", c.duid, kind, data, c.kind, c.data)
		}
	}

	for _, bad := range []string{"", "00:03", "00:03:zz", "0003000100005e005301", "00:3:00:01:ff"} {
		if _, _, err := splitDUID(bad); err == nil {
			t.Errorf("%q was accepted as a DUID", bad)
		}
	}
}
