package networkd

import (
	"strings"
	"testing"
)

// A DNSForwarder that listens on loopback is the host's own resolver, and the host is
// told so through networkd: the link's file names 127.0.0.1 as its DNS server and as the
// route for every name no other link claims. systemd-resolved reads that from networkd
// and reaches a loopback server through the loopback link, whichever link named it
// (ADR 0018).
func TestLoopbackForwarderIsTheHostResolver(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses: [192.0.2.1/24]
    - kind: DNSForwarder
      metadata: {name: lan}
      spec:
        listenOn: [lan, loopback]
        upstreams: [192.0.2.53]
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
Address=192.0.2.1/24
DNS=127.0.0.1
DNSDefaultRoute=yes
IPv6AcceptRA=no
`)
	if len(out.Warnings) != 0 {
		t.Errorf("warnings are %q, want none", out.Warnings)
	}
}

// The entry rides on every link regied gives an address to, not only on the links the
// forwarder listens on. resolved uses a link's servers only while the link is up with
// carrier and an address, and a bridge with no member connected has no carrier, so a
// host set up before its first client would have no resolver if the bridge alone carried
// it. Bridge ports hold no address and carry nothing.
func TestHostResolverRidesOnEveryAddressedLink(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: br-lan
        bridge:
          members: [eth1, eth2]
        addresses: [192.0.2.1/24]
    - kind: Interface
      metadata: {name: port}
      spec:
        ifname: eth2
        mtu: 9000
    - kind: DNSForwarder
      metadata: {name: lan}
      spec:
        listenOn: [lan, loopback]
        upstreams: [192.0.2.53]
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-wan.network", `# Generated by regied from Interface/wan. Do not edit.

[Match]
Name=eth0

[Network]
DNS=127.0.0.1
DNSDefaultRoute=yes
DHCP=ipv6
IPv6AcceptRA=yes

[DHCPv6]
WithoutRA=solicit
UseAddress=no
UseDNS=no
RapidCommit=yes
PrefixDelegationHint=::/56

[IPv6AcceptRA]
UseDNS=no
`)
	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=br-lan

[Network]
ConfigureWithoutCarrier=yes
Address=192.0.2.1/24
DNS=127.0.0.1
DNSDefaultRoute=yes
IPv6AcceptRA=no
`)
	assertFile(t, out, "50-regied-lan-eth1.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
LinkLocalAddressing=no
Bridge=br-lan
IPv6AcceptRA=no
`)
	assertFile(t, out, "50-regied-port.network", `# Generated by regied from Interface/port. Do not edit.

[Match]
Name=eth2

[Link]
MTUBytes=9000

[Network]
LinkLocalAddressing=no
Bridge=br-lan
IPv6AcceptRA=no
`)
}

// A forwarder that does not listen on loopback serves the segments below and nothing
// else: the host keeps whatever resolver it had, and no file says otherwise.
func TestForwarderWithoutLoopbackLeavesTheHostResolverAlone(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses: [192.0.2.1/24]
    - kind: DNSForwarder
      metadata: {name: lan}
      spec:
        listenOn: [lan]
        upstreams: [192.0.2.53]
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-lan.network", `# Generated by regied from Interface/lan. Do not edit.

[Match]
Name=eth1

[Network]
Address=192.0.2.1/24
IPv6AcceptRA=no
`)
}

// Listening on loopback with no Interface to carry the entry is not an error — dnsmasq
// answers on the loopback as declared — but the host will not be told to ask it, and
// that is said before the apply rather than discovered after it.
func TestLoopbackForwarderWithNoLinkToCarryItWarns(t *testing.T) {
	cfg := load(t, `
    - kind: DNSForwarder
      metadata: {name: local}
      spec:
        listenOn: [loopback]
        upstreams: [192.0.2.53]
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out)
	if len(out.Warnings) != 1 {
		t.Fatalf("warnings are %q, want one about the host's resolver", out.Warnings)
	}
	if !strings.Contains(out.Warnings[0], "DNSForwarder/local") || !strings.Contains(out.Warnings[0], "loopback") {
		t.Errorf("the warning names neither the forwarder nor loopback: %q", out.Warnings[0])
	}
}

// A member declared as an Interface of its own is still a port: it holds no address, so
// it carries nothing, and the bridge over it is what does.
func TestBridgePortsDoNotCarryTheHostResolver(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: port}
      spec:
        ifname: eth1
        mtu: 9000
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: br-lan
        bridge:
          members: [eth1]
    - kind: DNSForwarder
      metadata: {name: lan}
      spec:
        listenOn: [lan, loopback]
        upstreams: [192.0.2.53]
`)
	out := render(t, cfg, Runtime{})

	// The bridge itself carries it; the port does not.
	if len(out.Warnings) != 0 {
		t.Errorf("warnings are %q, want none: the bridge carries the entry", out.Warnings)
	}
	assertFile(t, out, "50-regied-port.network", `# Generated by regied from Interface/port. Do not edit.

[Match]
Name=eth1

[Link]
MTUBytes=9000

[Network]
LinkLocalAddressing=no
Bridge=br-lan
IPv6AcceptRA=no
`)
}
