package networkd

import (
	"net/netip"
	"strings"
	"testing"
)

// The two links a DS-Lite tunnel needs: the ip6tnl itself, and the underlay that carries
// it. The AFTR is named in the configuration and resolved by the apply engine, so the
// address it resolved to arrives as a runtime value.
func TestDSLiteTunnel(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
    - kind: DSLiteTunnel
      metadata: {name: dslite}
      spec:
        underlayRef: wan
        localAddressFrom:
          interfaceRef: wan
        aftrHost: aftr.example.net
        mtu: 1454
        ttl: 64
        defaultRoute:
          install: true
          metric: 0
`)
	out := render(t, cfg, Runtime{AFTRAddresses: map[string]netip.Addr{
		"dslite": netip.MustParseAddr("2001:db8:ffff::1"),
	}})

	assertNames(t, out, "50-regied-dslite.netdev", "50-regied-dslite.network", "50-regied-wan.network")

	assertFile(t, out, "50-regied-dslite.netdev", `# Generated by regied from DSLiteTunnel/dslite. Do not edit.

[NetDev]
Name=dslite
Kind=ip6tnl
MTUBytes=1454

[Tunnel]
Mode=ipip6
Local=slaac
Remote=2001:db8:ffff::1
TTL=64
EncapsulationLimit=none
`)
	assertFile(t, out, "50-regied-dslite.network", `# Generated by regied from DSLiteTunnel/dslite. Do not edit.

[Match]
Name=dslite

[Network]
LinkLocalAddressing=no
IPv6AcceptRA=no

[Route]
Destination=0.0.0.0/0
Metric=0
`)

	// The tunnel is stacked on its underlay, which is what makes Local=slaac the
	// underlay's own address.
	assertFile(t, out, "50-regied-wan.network", `# Generated by regied from Interface/wan. Do not edit.

[Match]
Name=eth0

[Network]
DHCP=ipv6
IPv6AcceptRA=yes
Tunnel=dslite

[DHCPv6]
WithoutRA=solicit
UseAddress=no
UseDNS=no
RapidCommit=yes
PrefixDelegationHint=::/56

[IPv6AcceptRA]
UseDNS=no
`)
	if len(out.Warnings) != 0 {
		t.Errorf("warnings are %q, want none", out.Warnings)
	}
}

// A statically addressed deployment writes both ends out, and then nothing has to be
// resolved at apply time. defaultRoute.install false leaves the main table alone.
func TestDSLiteTunnelWrittenOut(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        addresses:
          - "2001:db8:0:ff::2/64"
    - kind: DSLiteTunnel
      metadata: {name: dslite}
      spec:
        underlayRef: wan
        localAddress: "2001:db8:0:ff::2"
        aftrAddress: "2001:db8:ffff::1"
        defaultRoute:
          install: false
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-dslite.netdev", `# Generated by regied from DSLiteTunnel/dslite. Do not edit.

[NetDev]
Name=dslite
Kind=ip6tnl
MTUBytes=1454

[Tunnel]
Mode=ipip6
Local=2001:db8:0:ff::2
Remote=2001:db8:ffff::1
TTL=64
EncapsulationLimit=none
`)
	assertFile(t, out, "50-regied-dslite.network", `# Generated by regied from DSLiteTunnel/dslite. Do not edit.

[Match]
Name=dslite

[Network]
LinkLocalAddressing=no
IPv6AcceptRA=no
`)
}

// systemd 257 cannot take a tunnel's local address from a delegated prefix, so a
// localAddressFrom naming anything but the underlay is not rendered as it was written
// (ADR 0011). It is reported rather than dropped quietly.
func TestDSLiteTunnelLocalAddressFromAnotherInterface(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
        dhcpv6:
          prefixDelegation:
            prefixLength: 56
    - kind: Interface
      metadata: {name: lan}
      spec:
        ifname: eth1
        addresses:
          - fromDelegatedPrefix: {interfaceRef: wan, subnetID: 1}
    - kind: DSLiteTunnel
      metadata: {name: dslite}
      spec:
        underlayRef: wan
        localAddressFrom:
          interfaceRef: lan
        aftrAddress: "2001:db8:ffff::1"
`)
	out := render(t, cfg, Runtime{})

	if len(out.Warnings) != 1 || !strings.Contains(out.Warnings[0], "DSLiteTunnel/dslite") {
		t.Fatalf("warnings are %q, want one about the tunnel's local address", out.Warnings)
	}
	if !strings.Contains(out.Warnings[0], "Interface/wan") {
		t.Errorf("the warning does not say whose address is used instead: %q", out.Warnings[0])
	}
	assertFile(t, out, "50-regied-dslite.netdev", `# Generated by regied from DSLiteTunnel/dslite. Do not edit.

[NetDev]
Name=dslite
Kind=ip6tnl
MTUBytes=1454

[Tunnel]
Mode=ipip6
Local=slaac
Remote=2001:db8:ffff::1
TTL=64
EncapsulationLimit=none
`)
}

// A tunnel built from a name cannot be rendered before the name has been resolved.
func TestDSLiteTunnelMissingAFTRAddress(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
    - kind: DSLiteTunnel
      metadata: {name: dslite}
      spec:
        underlayRef: wan
        localAddress: "2001:db8:0:ff::2"
        aftrHost: aftr.example.net
`)
	_, err := Render(cfg, Runtime{})
	if err == nil {
		t.Fatal("rendered a tunnel whose AFTR name had not been resolved")
	}
	if !strings.Contains(err.Error(), "aftr.example.net") {
		t.Errorf("the error does not name the host: %v", err)
	}
}

// A policy becomes a default route in a table of its own and a rule selecting that table
// by mark. Both go on the uplink the traffic leaves by, so that they follow it up and
// down.
func TestEgressRoutePolicyOnATunnel(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
    - kind: DSLiteTunnel
      metadata: {name: dslite}
      spec:
        underlayRef: wan
        localAddress: "2001:db8:0:ff::2"
        aftrAddress: "2001:db8:ffff::1"
    - kind: EgressRoutePolicy
      metadata: {name: rest-via-dslite}
      spec:
        priority: 20
        egressRef: dslite
        sourceRanges: [192.0.2.0/24]
    - kind: EgressRoutePolicy
      metadata: {name: v6-via-dslite}
      spec:
        family: ipv6
        priority: 10
        egressRef: dslite
        sourceRanges: ["2001:db8:0:1::/64"]
        table: 42
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-dslite.network", `# Generated by regied from DSLiteTunnel/dslite. Do not edit.

[Match]
Name=dslite

[Network]
LinkLocalAddressing=no
IPv6AcceptRA=no

[Route]
Destination=0.0.0.0/0
Metric=0

[Route]
Destination=0.0.0.0/0
Table=100

[RoutingPolicyRule]
Family=ipv4
FirewallMark=256
Table=100
Priority=100

[Route]
Destination=::/0
Table=42

[RoutingPolicyRule]
Family=ipv6
FirewallMark=257
Table=42
Priority=42
`)
}

// networkd does not create the PPPoE link and does not address it. The file regied
// writes for it carries the routing a policy needs and nothing else, and says so.
func TestEgressRoutePolicyOnAPPPoESession(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
    - kind: PPPoESession
      metadata: {name: pppoe0}
      spec:
        interfaceRef: wan
        userIDFile: /etc/regied/secrets/pppoe-user-id
        passwordFile: /etc/regied/secrets/pppoe-password
    - kind: EgressRoutePolicy
      metadata: {name: upper-half-via-pppoe}
      spec:
        priority: 10
        egressRef: pppoe0
        sourceRanges: [192.0.2.128-192.0.2.255]
        mark: 4096
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out, "50-regied-pppoe0.network", "50-regied-wan.network")
	assertFile(t, out, "50-regied-pppoe0.network", `# Generated by regied from PPPoESession/pppoe0. Do not edit.
#
# pppd creates this link, names it and addresses it. regied writes this file only for
# the routes that leave by it: the static ones declared on the session, and the table an
# EgressRoutePolicy needs. KeepConfiguration keeps networkd from dropping what pppd
# installed.

[Match]
Name=pppoe0

[Network]
KeepConfiguration=yes

[Route]
Destination=0.0.0.0/0
Table=100

[RoutingPolicyRule]
Family=ipv4
FirewallMark=4096
Table=100
Priority=100
`)
}

// A PPPoE session no policy names needs nothing from networkd, and gets no file: the
// link stays unmanaged.
func TestPPPoESessionWithoutAPolicy(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
    - kind: PPPoESession
      metadata: {name: pppoe0}
      spec:
        interfaceRef: wan
        userIDFile: /etc/regied/secrets/pppoe-user-id
        passwordFile: /etc/regied/secrets/pppoe-password
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out, "50-regied-wan.network")
}

// A session's static routes are the same thing an Interface's are, and they go the same
// way: into the file this backend already writes for that link. pppd's option file
// cannot carry a route, so nothing else would install them.
func TestPPPoESessionRoutes(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
    - kind: PPPoESession
      metadata: {name: pppoe0}
      spec:
        interfaceRef: wan
        userIDFile: /etc/regied/secrets/pppoe-user-id
        passwordFile: /etc/regied/secrets/pppoe-password
        routes:
          - destination: 198.51.100.0/24
            via: 192.0.2.1
          - destination: 203.0.113.0/24
`)
	out := render(t, cfg, Runtime{})

	assertNames(t, out, "50-regied-pppoe0.network", "50-regied-wan.network")
	assertFile(t, out, "50-regied-pppoe0.network", `# Generated by regied from PPPoESession/pppoe0. Do not edit.
#
# pppd creates this link, names it and addresses it. regied writes this file only for
# the routes that leave by it: the static ones declared on the session, and the table an
# EgressRoutePolicy needs. KeepConfiguration keeps networkd from dropping what pppd
# installed.

[Match]
Name=pppoe0

[Network]
KeepConfiguration=yes

[Route]
Destination=198.51.100.0/24
Gateway=192.0.2.1

[Route]
Destination=203.0.113.0/24
`)
}

// Static routes and a policy's table share the link, and the static ones come first: a
// policy's default route is the one thing in its table that everything else falls
// through to.
func TestPPPoESessionRoutesAndPolicy(t *testing.T) {
	cfg := load(t, `
    - kind: Interface
      metadata: {name: wan}
      spec:
        ifname: eth0
    - kind: PPPoESession
      metadata: {name: pppoe0}
      spec:
        interfaceRef: wan
        userIDFile: /etc/regied/secrets/pppoe-user-id
        passwordFile: /etc/regied/secrets/pppoe-password
        routes:
          - destination: 198.51.100.0/24
            via: 192.0.2.1
    - kind: EgressRoutePolicy
      metadata: {name: upper-half-via-pppoe}
      spec:
        priority: 10
        egressRef: pppoe0
        sourceRanges: [192.0.2.128-192.0.2.255]
`)
	out := render(t, cfg, Runtime{})

	assertFile(t, out, "50-regied-pppoe0.network", `# Generated by regied from PPPoESession/pppoe0. Do not edit.
#
# pppd creates this link, names it and addresses it. regied writes this file only for
# the routes that leave by it: the static ones declared on the session, and the table an
# EgressRoutePolicy needs. KeepConfiguration keeps networkd from dropping what pppd
# installed.

[Match]
Name=pppoe0

[Network]
KeepConfiguration=yes

[Route]
Destination=198.51.100.0/24
Gateway=192.0.2.1

[Route]
Destination=0.0.0.0/0
Table=100

[RoutingPolicyRule]
Family=ipv4
FirewallMark=256
Table=100
Priority=100
`)
}
