// Package pppd builds pppd's configuration for the PPPoE sessions a configuration
// declares. systemd-networkd has no PPPoE, so this is the one link layer regied
// configures itself (ADR 0008).
//
// Rendering is a pure function of the validated configuration. Nothing here reads the
// kernel, starts a process, or opens a credential file: bringing the session up belongs
// to the apply engine, and the credentials reach this package as an argument.
package pppd

import (
	"fmt"
	"io/fs"
	"strings"
	"time"

	"github.com/yuanying/regied/internal/apis/v1alpha1"
	"github.com/yuanying/regied/internal/config"
)

// DefaultRoot is the directory regied's generated pppd configuration lives under. Every
// file below it belongs to regied and is rewritten on apply; nothing regied did not
// write is under it (ADR 0009).
const DefaultRoot = "/etc/regied"

// ownershipMarker is the first line of every file this package produces. It says who
// wrote the file, so that a file without it is somebody else's and is left alone.
const ownershipMarker = "# Generated by regied. Do not edit: every apply rewrites this file."

// File is one file to put on the host: where it goes, what is in it, and how it and the
// directory holding it are protected.
type File struct {
	Path    string
	Mode    fs.FileMode
	DirMode fs.FileMode
	Content string

	// Secret says the content holds a credential. Such a file is written, but its
	// content is never printed: not in --dry-run output, not in a diff, not in a log
	// line (ADR 0003).
	Secret bool
}

// Output is every PPPoE session, rendered.
type Output struct {
	Sessions []Session
}

// Files is the files whose content follows from the configuration alone. The credentials
// file is not among them: its content is not known until apply has read the credentials.
func (o *Output) Files() []File {
	files := make([]File, 0, len(o.Sessions))
	for _, session := range o.Sessions {
		files = append(files, session.Peer)
	}
	return files
}

// Session is one PPPoESession rendered.
//
// pppd is given both files, as two `file` options: the peer file, and the credentials
// file. Splitting them is what keeps the account name and the password out of everything
// regied prints — see ADR 0014.
type Session struct {
	// Name is the resource's name.
	Name string
	// Ifname is the kernel name of the link the session puts on the host. It is the
	// resource's name: pinning it is what stops a redial from moving the link between
	// ppp0 and ppp1 under everything that points at it.
	Ifname string
	// NIC is the Ethernet interface PPPoE runs over.
	NIC string

	Peer        File
	Credentials CredentialsFile
}

// CredentialsFile is the second options file, the one holding the account name and the
// password. The renderer names the files those values are in and never opens them; apply
// reads them and calls Render.
type CredentialsFile struct {
	// Name is the session's name, so that the file says which session it belongs to.
	Name string

	Path    string
	Mode    fs.FileMode
	DirMode fs.FileMode

	UserIDFile   string
	PasswordFile string
}

// Credentials are the values behind UserIDFile and PasswordFile. They live in memory
// only as long as writing the file takes.
type Credentials struct {
	UserID   string
	Password string
}

// Render builds the content of the credentials file.
//
// A trailing newline is not part of a value: a credential read from a file almost always
// has one, and left in place it would end the pppd directive early.
func (c CredentialsFile) Render(credentials Credentials) (File, error) {
	userID := strings.TrimRight(credentials.UserID, "\r\n")
	password := strings.TrimRight(credentials.Password, "\r\n")

	for _, field := range []struct{ name, value string }{
		{"user ID", userID}, {"password", password},
	} {
		if field.value == "" {
			return File{}, fmt.Errorf("the %s is empty", field.name)
		}
		if strings.ContainsAny(field.value, "\r\n") {
			// One directive is one line. Writing the value anyway would turn the rest of
			// it into pppd options.
			return File{}, fmt.Errorf("the %s holds a line break", field.name)
		}
	}

	var b strings.Builder
	b.WriteString(ownershipMarker + "\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# PPPoESession/%s. Both values are credentials (ADR 0003), which is why\n", c.Name)
	b.WriteString("# this file is separate from the peer file and readable only by its owner.\n\n")
	fmt.Fprintf(&b, "user %s\n", quote(userID))
	fmt.Fprintf(&b, "password %s\n", quote(password))

	return File{
		Path:    c.Path,
		Mode:    c.Mode,
		DirMode: c.DirMode,
		Content: b.String(),
		Secret:  true,
	}, nil
}

// quote writes a value as pppd reads a quoted option: in double quotes, with a backslash
// before a backslash or a quote.
func quote(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + replacer.Replace(value) + `"`
}

// Option changes where the rendered files are put.
type Option func(*options)

type options struct {
	root string
}

// WithRoot puts the generated files under a directory other than DefaultRoot.
func WithRoot(dir string) Option {
	return func(o *options) { o.root = dir }
}

func resolveOptions(opts []Option) options {
	resolved := options{root: DefaultRoot}
	for _, opt := range opts {
		opt(&resolved)
	}
	return resolved
}

// How long pppd waits before redialling, when the session says nothing.
const defaultHoldoff = v1alpha1.DefaultPPPoEHoldoffSeconds * time.Second

// How often pppd asks the peer whether it is still there, and how many unanswered asks
// end the session. Nothing in the schema sets these, and without them a session that
// died silently is never noticed and persist never fires.
const (
	lcpEchoInterval = 10
	lcpEchoFailure  = 5
)

// Render builds the configuration of every PPPoESession in cfg.
func Render(cfg *config.Config, opts ...Option) *Output {
	resolved := resolveOptions(opts)
	sessions := config.ResourcesOf[*v1alpha1.PPPoESessionSpec](cfg)

	out := &Output{}
	for _, session := range sessions {
		out.Sessions = append(out.Sessions, renderSession(cfg, resolved, session))
	}
	return out
}

func renderSession(cfg *config.Config, opts options, session config.Named[*v1alpha1.PPPoESessionSpec]) Session {
	spec := session.Spec
	rendered := Session{
		Name:   session.Name,
		Ifname: session.Name,
		NIC:    ifnameOf(cfg, spec.InterfaceRef),
		Peer: File{
			Path:    opts.root + "/ppp/peers/" + session.Name + ".conf",
			Mode:    0o644,
			DirMode: 0o755,
		},
		Credentials: CredentialsFile{
			Name:         session.Name,
			Path:         opts.root + "/ppp/credentials/" + session.Name + ".conf",
			Mode:         0o600,
			DirMode:      0o700,
			UserIDFile:   spec.UserIDFile,
			PasswordFile: spec.PasswordFile,
		},
	}
	rendered.Peer.Content = peerFile(rendered, spec)
	return rendered
}

// peerFile writes the options that are not credentials.
//
// spec.routes is not among them. A pppd options file cannot install a route, so the
// static routes written on a session are left for the apply engine to put on the link
// once it is up.
func peerFile(session Session, spec *v1alpha1.PPPoESessionSpec) string {
	var b strings.Builder
	b.WriteString(ownershipMarker + "\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# PPPoESession/%s. No credential appears here. The account name and the\n", session.Name)
	b.WriteString("# password are in a second options file, given to pppd alongside this one.\n\n")

	// rp-pppoe.so is the plugin name ppp 2.5 still answers to on the target platform
	// (ADR 0011), and nic-<interface> is how it is told which link to dial over.
	b.WriteString("plugin rp-pppoe.so\n")
	fmt.Fprintf(&b, "nic-%s\n\n", session.NIC)

	b.WriteString("# The link is named after the resource, so a redial does not rename it and\n")
	b.WriteString("# nothing that points at it has to follow.\n")
	fmt.Fprintf(&b, "ifname %s\n", session.Ifname)
	fmt.Fprintf(&b, "linkname %s\n\n", session.Ifname)

	mtu := spec.MTUOrDefault()
	fmt.Fprintf(&b, "mtu %d\n", mtu)
	fmt.Fprintf(&b, "mru %d\n\n", mtu)

	// The peer authenticates us and not the other way round, the address comes from the
	// peer, and IPv6 does not run over this link: the schema has no field for it, and
	// the IPv6 of a host with a PPPoE uplink comes from the interface underneath.
	b.WriteString("noauth\n")
	b.WriteString("noipdefault\n")
	b.WriteString("noipv6\n")
	if spec.UseDNSEnabled() {
		b.WriteString("usepeerdns\n")
	}
	b.WriteString("\n")

	if spec.DefaultRoute.InstallEnabled() {
		b.WriteString("defaultroute\n")
		// A metric of zero is pppd's own default; writing it would say something the
		// configuration did not.
		if metric := spec.DefaultRoute.MetricOrDefault(); metric != 0 {
			fmt.Fprintf(&b, "defaultroute-metric %d\n", metric)
		}
	} else {
		b.WriteString("nodefaultroute\n")
	}

	if spec.PersistEnabled() {
		b.WriteString("\n")
		b.WriteString("# Redial when the session drops, and notice that it dropped: without LCP\n")
		b.WriteString("# echoes a session that died silently is never redialled.\n")
		b.WriteString("persist\n")
		fmt.Fprintf(&b, "holdoff %d\n", int(spec.Holdoff.OrDefault(defaultHoldoff).Seconds()))
		b.WriteString("maxfail 0\n")
		fmt.Fprintf(&b, "lcp-echo-interval %d\n", lcpEchoInterval)
		fmt.Fprintf(&b, "lcp-echo-failure %d\n", lcpEchoFailure)
	}

	return b.String()
}

// ifnameOf is the kernel name of the interface a session runs over. Validation has
// already resolved the reference; the fallback is there so that a Config built by hand
// cannot make this panic.
func ifnameOf(cfg *config.Config, ref string) string {
	resource := cfg.Lookup(v1alpha1.KindInterface, ref)
	if resource == nil {
		return ref
	}
	spec, ok := resource.Spec.(*v1alpha1.InterfaceSpec)
	if !ok {
		return ref
	}
	return spec.Ifname
}
